name: cnb-tags
on:
  push:
    tags:
      - '*'
env:
  version: ${{ github.ref_name }}
jobs:
  builds:
    runs-on: ubuntu-24.04
    permissions: write-all
    name: build
    steps:
      - uses: actions/checkout@v4
      - name: dagger=0.15.2
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.15.2 sh
      
      # work around other runner's logging out removing credentials
      # https://github.com/docker/login-action/issues/173#issuecomment-1079688020
      - name: Set DOCKER_CONFIG
        run: |
          id=docker_configs/${RANDOM}
          mkdir -p $HOME/${id}/.docker
          echo "DOCKER_CONFIG=$HOME/${id}/.docker" >> $GITHUB_ENV
      - uses: docker/login-action@v3
        name: login=ghcr.io
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      - name: Pack Build
        uses: dfreilich/pack-action@v2.1.1
        with:
          args: 'build test_img --builder paketobuildpacks/builder-jammy-tiny'
